apiVersion: v1
kind: Pod
metadata:
  name: hey-benchmark
  namespace: opendatahub
  labels:
    app: hey-benchmark
spec:
  containers:
  - name: hey
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command:
    - /bin/sh
    - -c
    - |
      # Install hey tool
      curl -L https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 -o /usr/local/bin/hey
      chmod +x /usr/local/bin/hey
      # Keep pod running
      echo "hey tool installed. Ready for benchmarking."
      sleep infinity
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
  restartPolicy: Never
